// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETS_CPACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_CPACKETS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace CPackets {

struct C00PacketKeepAlive;
struct C00PacketKeepAliveBuilder;

struct C01PacketAuthenticate;
struct C01PacketAuthenticateBuilder;

struct CPacket;
struct CPacketBuilder;

enum Packets : uint8_t {
  Packets_NONE = 0,
  Packets_C00PacketKeepAlive = 1,
  Packets_C01PacketAuthenticate = 2,
  Packets_MIN = Packets_NONE,
  Packets_MAX = Packets_C01PacketAuthenticate
};

inline const Packets (&EnumValuesPackets())[3] {
  static const Packets values[] = {
    Packets_NONE,
    Packets_C00PacketKeepAlive,
    Packets_C01PacketAuthenticate
  };
  return values;
}

inline const char * const *EnumNamesPackets() {
  static const char * const names[4] = {
    "NONE",
    "C00PacketKeepAlive",
    "C01PacketAuthenticate",
    nullptr
  };
  return names;
}

inline const char *EnumNamePackets(Packets e) {
  if (::flatbuffers::IsOutRange(e, Packets_NONE, Packets_C01PacketAuthenticate)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPackets()[index];
}

template<typename T> struct PacketsTraits {
  static const Packets enum_value = Packets_NONE;
};

template<> struct PacketsTraits<CPackets::C00PacketKeepAlive> {
  static const Packets enum_value = Packets_C00PacketKeepAlive;
};

template<> struct PacketsTraits<CPackets::C01PacketAuthenticate> {
  static const Packets enum_value = Packets_C01PacketAuthenticate;
};

bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type);
bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct C00PacketKeepAlive FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C00PacketKeepAliveBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct C00PacketKeepAliveBuilder {
  typedef C00PacketKeepAlive Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C00PacketKeepAliveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C00PacketKeepAlive> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C00PacketKeepAlive>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C00PacketKeepAlive> CreateC00PacketKeepAlive(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C00PacketKeepAliveBuilder builder_(_fbb);
  return builder_.Finish();
}

struct C01PacketAuthenticate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C01PacketAuthenticateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNAME = 4,
    VT_UPASS = 6
  };
  const ::flatbuffers::String *uname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNAME);
  }
  const ::flatbuffers::String *upass() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UPASS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNAME) &&
           verifier.VerifyString(uname()) &&
           VerifyOffset(verifier, VT_UPASS) &&
           verifier.VerifyString(upass()) &&
           verifier.EndTable();
  }
};

struct C01PacketAuthenticateBuilder {
  typedef C01PacketAuthenticate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uname(::flatbuffers::Offset<::flatbuffers::String> uname) {
    fbb_.AddOffset(C01PacketAuthenticate::VT_UNAME, uname);
  }
  void add_upass(::flatbuffers::Offset<::flatbuffers::String> upass) {
    fbb_.AddOffset(C01PacketAuthenticate::VT_UPASS, upass);
  }
  explicit C01PacketAuthenticateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C01PacketAuthenticate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C01PacketAuthenticate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C01PacketAuthenticate> CreateC01PacketAuthenticate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> uname = 0,
    ::flatbuffers::Offset<::flatbuffers::String> upass = 0) {
  C01PacketAuthenticateBuilder builder_(_fbb);
  builder_.add_upass(upass);
  builder_.add_uname(uname);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<C01PacketAuthenticate> CreateC01PacketAuthenticateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *uname = nullptr,
    const char *upass = nullptr) {
  auto uname__ = uname ? _fbb.CreateString(uname) : 0;
  auto upass__ = upass ? _fbb.CreateString(upass) : 0;
  return CPackets::CreateC01PacketAuthenticate(
      _fbb,
      uname__,
      upass__);
}

struct CPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKETS_TYPE = 4,
    VT_PACKETS = 6
  };
  CPackets::Packets packets_type() const {
    return static_cast<CPackets::Packets>(GetField<uint8_t>(VT_PACKETS_TYPE, 0));
  }
  const void *packets() const {
    return GetPointer<const void *>(VT_PACKETS);
  }
  template<typename T> const T *packets_as() const;
  const CPackets::C00PacketKeepAlive *packets_as_C00PacketKeepAlive() const {
    return packets_type() == CPackets::Packets_C00PacketKeepAlive ? static_cast<const CPackets::C00PacketKeepAlive *>(packets()) : nullptr;
  }
  const CPackets::C01PacketAuthenticate *packets_as_C01PacketAuthenticate() const {
    return packets_type() == CPackets::Packets_C01PacketAuthenticate ? static_cast<const CPackets::C01PacketAuthenticate *>(packets()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKETS_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKETS) &&
           VerifyPackets(verifier, packets(), packets_type()) &&
           verifier.EndTable();
  }
};

template<> inline const CPackets::C00PacketKeepAlive *CPacket::packets_as<CPackets::C00PacketKeepAlive>() const {
  return packets_as_C00PacketKeepAlive();
}

template<> inline const CPackets::C01PacketAuthenticate *CPacket::packets_as<CPackets::C01PacketAuthenticate>() const {
  return packets_as_C01PacketAuthenticate();
}

struct CPacketBuilder {
  typedef CPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_packets_type(CPackets::Packets packets_type) {
    fbb_.AddElement<uint8_t>(CPacket::VT_PACKETS_TYPE, static_cast<uint8_t>(packets_type), 0);
  }
  void add_packets(::flatbuffers::Offset<void> packets) {
    fbb_.AddOffset(CPacket::VT_PACKETS, packets);
  }
  explicit CPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CPacket> CreateCPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CPackets::Packets packets_type = CPackets::Packets_NONE,
    ::flatbuffers::Offset<void> packets = 0) {
  CPacketBuilder builder_(_fbb);
  builder_.add_packets(packets);
  builder_.add_packets_type(packets_type);
  return builder_.Finish();
}

inline bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type) {
  switch (type) {
    case Packets_NONE: {
      return true;
    }
    case Packets_C00PacketKeepAlive: {
      auto ptr = reinterpret_cast<const CPackets::C00PacketKeepAlive *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packets_C01PacketAuthenticate: {
      auto ptr = reinterpret_cast<const CPackets::C01PacketAuthenticate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPackets(
        verifier,  values->Get(i), types->GetEnum<Packets>(i))) {
      return false;
    }
  }
  return true;
}

inline const CPackets::CPacket *GetCPacket(const void *buf) {
  return ::flatbuffers::GetRoot<CPackets::CPacket>(buf);
}

inline const CPackets::CPacket *GetSizePrefixedCPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<CPackets::CPacket>(buf);
}

inline bool VerifyCPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CPackets::CPacket>(nullptr);
}

inline bool VerifySizePrefixedCPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CPackets::CPacket>(nullptr);
}

inline void FinishCPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CPackets::CPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CPackets::CPacket> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CPackets

#endif  // FLATBUFFERS_GENERATED_PACKETS_CPACKETS_H_
