// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct S00PacketKeepAlive;
struct S00PacketKeepAliveBuilder;

struct Packet;
struct PacketBuilder;

enum Packets : uint8_t {
  Packets_NONE = 0,
  Packets_S00PacketKeepAlive = 1,
  Packets_MIN = Packets_NONE,
  Packets_MAX = Packets_S00PacketKeepAlive
};

inline const Packets (&EnumValuesPackets())[2] {
  static const Packets values[] = {
    Packets_NONE,
    Packets_S00PacketKeepAlive
  };
  return values;
}

inline const char * const *EnumNamesPackets() {
  static const char * const names[3] = {
    "NONE",
    "S00PacketKeepAlive",
    nullptr
  };
  return names;
}

inline const char *EnumNamePackets(Packets e) {
  if (::flatbuffers::IsOutRange(e, Packets_NONE, Packets_S00PacketKeepAlive)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPackets()[index];
}

template<typename T> struct PacketsTraits {
  static const Packets enum_value = Packets_NONE;
};

template<> struct PacketsTraits<S00PacketKeepAlive> {
  static const Packets enum_value = Packets_S00PacketKeepAlive;
};

bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type);
bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct S00PacketKeepAlive FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S00PacketKeepAliveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST = 4
  };
  int8_t test() const {
    return GetField<int8_t>(VT_TEST, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TEST, 1) &&
           verifier.EndTable();
  }
};

struct S00PacketKeepAliveBuilder {
  typedef S00PacketKeepAlive Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_test(int8_t test) {
    fbb_.AddElement<int8_t>(S00PacketKeepAlive::VT_TEST, test, 0);
  }
  explicit S00PacketKeepAliveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S00PacketKeepAlive> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S00PacketKeepAlive>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S00PacketKeepAlive> CreateS00PacketKeepAlive(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int8_t test = 0) {
  S00PacketKeepAliveBuilder builder_(_fbb);
  builder_.add_test(test);
  return builder_.Finish();
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PACKETS_TYPE = 6,
    VT_PACKETS = 8
  };
  int8_t id() const {
    return GetField<int8_t>(VT_ID, 0);
  }
  Packets packets_type() const {
    return static_cast<Packets>(GetField<uint8_t>(VT_PACKETS_TYPE, 0));
  }
  const void *packets() const {
    return GetPointer<const void *>(VT_PACKETS);
  }
  template<typename T> const T *packets_as() const;
  const S00PacketKeepAlive *packets_as_S00PacketKeepAlive() const {
    return packets_type() == Packets_S00PacketKeepAlive ? static_cast<const S00PacketKeepAlive *>(packets()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_PACKETS_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKETS) &&
           VerifyPackets(verifier, packets(), packets_type()) &&
           verifier.EndTable();
  }
};

template<> inline const S00PacketKeepAlive *Packet::packets_as<S00PacketKeepAlive>() const {
  return packets_as_S00PacketKeepAlive();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int8_t id) {
    fbb_.AddElement<int8_t>(Packet::VT_ID, id, 0);
  }
  void add_packets_type(Packets packets_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_PACKETS_TYPE, static_cast<uint8_t>(packets_type), 0);
  }
  void add_packets(::flatbuffers::Offset<void> packets) {
    fbb_.AddOffset(Packet::VT_PACKETS, packets);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int8_t id = 0,
    Packets packets_type = Packets_NONE,
    ::flatbuffers::Offset<void> packets = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_packets(packets);
  builder_.add_packets_type(packets_type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type) {
  switch (type) {
    case Packets_NONE: {
      return true;
    }
    case Packets_S00PacketKeepAlive: {
      auto ptr = reinterpret_cast<const S00PacketKeepAlive *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPackets(
        verifier,  values->Get(i), types->GetEnum<Packets>(i))) {
      return false;
    }
  }
  return true;
}

inline const Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<Packet>(buf);
}

inline const Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Packet>(buf);
}

inline bool VerifyPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Packet>(nullptr);
}

inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Packet> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PACKETS_H_