// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETS_SPACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_SPACKETS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace SPackets {

struct S00PacketKeepAlive;
struct S00PacketKeepAliveBuilder;

struct S01PacketAuthenticate;
struct S01PacketAuthenticateBuilder;

struct SPacket;
struct SPacketBuilder;

enum Packets : uint8_t {
  Packets_NONE = 0,
  Packets_S00PacketKeepAlive = 1,
  Packets_S01PacketAuthenticate = 2,
  Packets_MIN = Packets_NONE,
  Packets_MAX = Packets_S01PacketAuthenticate
};

inline const Packets (&EnumValuesPackets())[3] {
  static const Packets values[] = {
    Packets_NONE,
    Packets_S00PacketKeepAlive,
    Packets_S01PacketAuthenticate
  };
  return values;
}

inline const char * const *EnumNamesPackets() {
  static const char * const names[4] = {
    "NONE",
    "S00PacketKeepAlive",
    "S01PacketAuthenticate",
    nullptr
  };
  return names;
}

inline const char *EnumNamePackets(Packets e) {
  if (::flatbuffers::IsOutRange(e, Packets_NONE, Packets_S01PacketAuthenticate)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPackets()[index];
}

template<typename T> struct PacketsTraits {
  static const Packets enum_value = Packets_NONE;
};

template<> struct PacketsTraits<SPackets::S00PacketKeepAlive> {
  static const Packets enum_value = Packets_S00PacketKeepAlive;
};

template<> struct PacketsTraits<SPackets::S01PacketAuthenticate> {
  static const Packets enum_value = Packets_S01PacketAuthenticate;
};

bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type);
bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct S00PacketKeepAlive FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S00PacketKeepAliveBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct S00PacketKeepAliveBuilder {
  typedef S00PacketKeepAlive Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit S00PacketKeepAliveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S00PacketKeepAlive> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S00PacketKeepAlive>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S00PacketKeepAlive> CreateS00PacketKeepAlive(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  S00PacketKeepAliveBuilder builder_(_fbb);
  return builder_.Finish();
}

struct S01PacketAuthenticate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S01PacketAuthenticateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4
  };
  const ::flatbuffers::String *uid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UID) &&
           verifier.VerifyString(uid()) &&
           verifier.EndTable();
  }
};

struct S01PacketAuthenticateBuilder {
  typedef S01PacketAuthenticate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(::flatbuffers::Offset<::flatbuffers::String> uid) {
    fbb_.AddOffset(S01PacketAuthenticate::VT_UID, uid);
  }
  explicit S01PacketAuthenticateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S01PacketAuthenticate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S01PacketAuthenticate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S01PacketAuthenticate> CreateS01PacketAuthenticate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> uid = 0) {
  S01PacketAuthenticateBuilder builder_(_fbb);
  builder_.add_uid(uid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<S01PacketAuthenticate> CreateS01PacketAuthenticateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *uid = nullptr) {
  auto uid__ = uid ? _fbb.CreateString(uid) : 0;
  return SPackets::CreateS01PacketAuthenticate(
      _fbb,
      uid__);
}

struct SPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKETS_TYPE = 4,
    VT_PACKETS = 6
  };
  SPackets::Packets packets_type() const {
    return static_cast<SPackets::Packets>(GetField<uint8_t>(VT_PACKETS_TYPE, 0));
  }
  const void *packets() const {
    return GetPointer<const void *>(VT_PACKETS);
  }
  template<typename T> const T *packets_as() const;
  const SPackets::S00PacketKeepAlive *packets_as_S00PacketKeepAlive() const {
    return packets_type() == SPackets::Packets_S00PacketKeepAlive ? static_cast<const SPackets::S00PacketKeepAlive *>(packets()) : nullptr;
  }
  const SPackets::S01PacketAuthenticate *packets_as_S01PacketAuthenticate() const {
    return packets_type() == SPackets::Packets_S01PacketAuthenticate ? static_cast<const SPackets::S01PacketAuthenticate *>(packets()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKETS_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKETS) &&
           VerifyPackets(verifier, packets(), packets_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SPackets::S00PacketKeepAlive *SPacket::packets_as<SPackets::S00PacketKeepAlive>() const {
  return packets_as_S00PacketKeepAlive();
}

template<> inline const SPackets::S01PacketAuthenticate *SPacket::packets_as<SPackets::S01PacketAuthenticate>() const {
  return packets_as_S01PacketAuthenticate();
}

struct SPacketBuilder {
  typedef SPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_packets_type(SPackets::Packets packets_type) {
    fbb_.AddElement<uint8_t>(SPacket::VT_PACKETS_TYPE, static_cast<uint8_t>(packets_type), 0);
  }
  void add_packets(::flatbuffers::Offset<void> packets) {
    fbb_.AddOffset(SPacket::VT_PACKETS, packets);
  }
  explicit SPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SPacket> CreateSPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SPackets::Packets packets_type = SPackets::Packets_NONE,
    ::flatbuffers::Offset<void> packets = 0) {
  SPacketBuilder builder_(_fbb);
  builder_.add_packets(packets);
  builder_.add_packets_type(packets_type);
  return builder_.Finish();
}

inline bool VerifyPackets(::flatbuffers::Verifier &verifier, const void *obj, Packets type) {
  switch (type) {
    case Packets_NONE: {
      return true;
    }
    case Packets_S00PacketKeepAlive: {
      auto ptr = reinterpret_cast<const SPackets::S00PacketKeepAlive *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Packets_S01PacketAuthenticate: {
      auto ptr = reinterpret_cast<const SPackets::S01PacketAuthenticate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketsVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPackets(
        verifier,  values->Get(i), types->GetEnum<Packets>(i))) {
      return false;
    }
  }
  return true;
}

inline const SPackets::SPacket *GetSPacket(const void *buf) {
  return ::flatbuffers::GetRoot<SPackets::SPacket>(buf);
}

inline const SPackets::SPacket *GetSizePrefixedSPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SPackets::SPacket>(buf);
}

inline bool VerifySPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SPackets::SPacket>(nullptr);
}

inline bool VerifySizePrefixedSPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SPackets::SPacket>(nullptr);
}

inline void FinishSPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SPackets::SPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SPackets::SPacket> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SPackets

#endif  // FLATBUFFERS_GENERATED_PACKETS_SPACKETS_H_
